name: LawOfficeofadammkent
favicon: null
layout_spectrum: 0.3300548808183521
typography_spectrum: 0.9536947291344404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b5f83'
    - '#80abbe'
    - '#528da8'
    - '#b6cfda'
  brandStrength: 0.11383414594456553
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
